name: Fetch Mushroomsoft Employees Data

on: 
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Running Script
        run: node ./scripts/mushroomsoftEmployeesData.js      

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: Automated Change
          commit_user_name: Juanpa Cortez [GitHub Actions]
          commit_author: juanpa
          
        
